CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Books" (
    "IdBook" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "ISBN" text NOT NULL,
    "Price" double precision NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("IdBook")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231003171235_AddBookToDb', '8.0.0-rc.1.23419.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Books" ADD "Author" text NOT NULL DEFAULT '';

ALTER TABLE "Books" ADD "PageCount" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231003173346_AddTwoPropsToBook', '8.0.0-rc.1.23419.6');

COMMIT;

